# Generated by Django 4.2.20 on 2025-04-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Processamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.FloatField()),
                ('num2', models.FloatField()),
                ('num3', models.FloatField()),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('FINALIZADO', 'Finalizado')], default='PROCESSANDO')),
                ('average', models.FloatField(db_column='media', default=0)),
                ('median', models.FloatField(db_column='mediana', default=0)),
            ],
            options={
                'db_table': 'processamento',
            },
        ),
    ]
