# Generated by Django 4.2.20 on 2025-04-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_processamento_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamento',
            name='status',
            field=models.CharField(choices=[('PROCESSANDO', 'Processando'), ('FINALIZADO', 'Finalizado')], default='PROCESSANDO'),
        ),
    ]
