FROM python:3.13

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos do projeto
COPY . /app

# Instala as dependências
RUN pip install --upgrade pip && \
    pip install -r back/requirements.txt

# Ajusta o PYTHONPATH para encontrar o projeto Django
ENV PYTHONPATH="${PYTHONPATH}:/app/back"

# Define a variável de ambiente do Django
ENV DJANGO_SETTINGS_MODULE=back.settings

# Comando padrão para o container do backend
CMD ["python", "back/manage.py", "runserver", "0.0.0.0:8000"]