FROM node:20-alpine as builder

WORKDIR /app

COPY front/package.json front/package-lock.json ./

RUN npm install

COPY front .
RUN npm run build --prod

FROM nginx:alpine
COPY --from=builder app/dist/front/browser /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/nginx.conf
COPY front/mime.types /etc/nginx/mime.types
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]