FROM python:3.13

# Define diretório de trabalho
WORKDIR /app

# Copia todos os arquivos (incluindo o back e o worker)
COPY . .

# Instala as dependências (ajuste se tiver requirements separados)
RUN pip install --upgrade pip \
    && pip install -r worker/requirements.txt

# Comando padrão: iniciar Celery com o app Django do worker
CMD ["celery", "-A", "worker.worker.worker", "worker", "--loglevel=info"]
