FROM python:3.13

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos do projeto
COPY . /app

# Instala as dependências
RUN pip install --upgrade pip && \
    pip install -r back/requirements.txt


# Ajusta o PYTHONPATH para encontrar o projeto Django
ENV PYTHONPATH="${PYTHONPATH}:/app/back/celeryproject"